name: sukh_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.2.1
  dropdown_button2: ^2.3.8
  google_fonts: ^6.3.3
  http: ^1.6.0
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  top_snackbar_flutter: ^3.3.0
  go_router: ^17.0.0
  shared_preferences: ^2.1.1
  equatable: ^2.0.5
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5
  rename: ^3.1.0
  connectivity_plus: ^7.0.0
  shake: ^3.0.0
  local_auth: ^3.0.0
  snow_fall_animation: ^0.0.1+2
  socket_io_client: ^2.0.3+1
  flutter_svg: ^2.0.9
  liquid_glass_renderer: ^0.2.0-dev.4
  syncfusion_flutter_pdfviewer: ^28.1.36
  provider: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/img/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/fonts/
    - lib/assets/img/
    - lib/assets/pdf/

  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Inter-Bold.ttf
          weight: 700
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
